Fix #23, fix #31. Add bar chart, calendar, and style front page
audio-engineer/nova-dashboard-front-end pull request #32
Opened 2024-10-30 21:44 UTC by Danar435

2024-10-30 23:12 UTC, Danar435 commented
I decided to stay up for another hour and add some logic behind the buttons, now you should be able to cycle between the different charts we have

2024-11-02 09:09 UTC, audio-engineer requested changes
A couple of changes requested. Do the corrections and we will merge it. You can remove the arrow buttons and do the other changes that we talked about yesterday in a future commit.

2024-11-02 09:09 UTC, audio-engineer commented on components/client/bar-chart.tsx
> +      /* eslint-disable-next-line @typescript-eslint/prefer-readonly-parameter-types */
@Danar435 Line comments in JavaScript/TypeScript are usually `//`. Block comments are `/** ... */`. `/* ... */` works but is unconventional.

2024-11-02 09:09 UTC, audio-engineer commented on components/client/home.tsx
> +"use client";
@Danar435 See comment above.

2024-11-02 09:09 UTC, audio-engineer commented on components/client/home.tsx
> +  ];
@Danar435 bad, bad... Markup belongs to markup (`return()`)

2024-11-02 09:09 UTC, audio-engineer commented on components/client/home.tsx
> +  const PointerIncrement = 1;
@Danar435 is this a type or a variable? Variables use camelCase, types PascalCase

2024-11-02 09:09 UTC, audio-engineer commented on components/client/home.tsx
> +  const [pointer, setPointer] = useState(InitialPointer);
@Danar435 Ok now I see the only purpose of `initialPointer` is to set the default state. Just use a `0` literal. Rule of thumb: Only if you use a value more than once should you need a variable or constant.

2024-11-07 16:04 UTC, audio-engineer commented
@Danar435 I suggest you close this PR. I already implemented all of your changes myself, making this commit redundant.

2024-11-07 16:51 UTC, closed without merging